version: "3.8"

services:
  front:
    container_name: ayclass-front
    build:
      context: .
      dockerfile: ./dockerfile
      #target: development
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
